-- Run once in the dedicated Supabase project named llm-cache-audit.
-- It is safe against the project's current empty, six-column starter table.
create table if not exists public.llm_call_logs (
  id bigint generated by default as identity primary key,
  prompt_name text not null,
  input_text text not null,
  output_text text not null,
  tokens_used integer not null check (tokens_used between 300 and 900),
  model text not null,
  provider text not null,
  created_at timestamptz not null default now()
);

-- Bring the pre-created empty table up to the complete requested schema.
alter table public.llm_call_logs add column if not exists model text;
alter table public.llm_call_logs add column if not exists provider text;
update public.llm_call_logs
set model = coalesce(model, 'gpt-4.1-mini'),
    provider = coalesce(provider, 'OpenAI')
where model is null or provider is null;
alter table public.llm_call_logs alter column model set not null;
alter table public.llm_call_logs alter column provider set not null;

-- 70 calls, one exact fixed input: high repeat rate.
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, tokens_used, model, provider, created_at)
select
  'faq_bot',
  'Return the standard DemoShop FAQ answer set for the public help center.',
  (array[
    'Standard help-center summary returned: shipping, returns, billing, and account access.',
    'Public FAQ response served with the standard DemoShop support policies.',
    'Fixed FAQ answer set returned without processing any user data.'
  ])[1 + ((i - 1) % 3)],
  360 + ((i * 17) % 250),
  'gpt-4.1-mini',
  'OpenAI',
  now() - ((i - 1) % 7) * interval '1 day'
        - ((i * 37) % 1080) * interval '1 minute'
from generate_series(1, 70) as sample(i);

-- 65 calls across the five exact dropdown-derived inputs used by the source.
with category_samples as (
  select
    i,
    (array[
      'Catalog category: electronics. Writing style: precise and feature-led.',
      'Catalog category: home-kitchen. Writing style: warm and practical.',
      'Catalog category: fitness. Writing style: energetic and motivating.',
      'Catalog category: beauty. Writing style: polished and sensory.',
      'Catalog category: books. Writing style: curious and editorial.'
    ])[1 + ((i - 1) % 5)] as category_input,
    (array['electronics', 'home-kitchen', 'fitness', 'beauty', 'books'])
      [1 + ((i - 1) % 5)] as category_name
  from generate_series(1, 65) as sample(i)
)
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, tokens_used, model, provider, created_at)
select
  'product_description_generator',
  category_input,
  'Generated a generic 90-word DemoShop catalog description for the ' || category_name || ' category.',
  420 + ((i * 19) % 330),
  'gpt-4.1-mini',
  'OpenAI',
  now() - ((i + 2) % 7) * interval '1 day'
        - ((i * 53) % 1020) * interval '1 minute'
from category_samples;

-- 45 distinct fake user/account inputs: near-zero repeat rate.
with fake_profiles as (
  select
    i,
    (array[
      'Avery Chen', 'Jordan Patel', 'Morgan Lee', 'Riley Garcia',
      'Casey Brown', 'Taylor Kim', 'Quinn Davis', 'Cameron Singh',
      'Skyler Wilson', 'Reese Martinez', 'Parker Nguyen', 'Rowan Clark',
      'Emerson Hall', 'Finley Robinson', 'Hayden Lewis', 'Dakota Young',
      'Sage Walker', 'Blake Hernandez', 'River King', 'Charlie Scott',
      'Alexis Green', 'Jamie Adams', 'Drew Baker', 'Kendall Nelson',
      'Robin Carter', 'Logan Mitchell', 'Arden Perez', 'Micah Roberts',
      'Ellis Brooks', 'Marley Howard', 'Remy Ward', 'Jules Torres',
      'Noel Peterson', 'Lane Gray', 'Frankie Ramirez', 'Kai James',
      'Shiloh Watson', 'Bellamy Foster', 'Ari Bennett', 'Phoenix Reed',
      'Tatum Cooper', 'Rory Bailey', 'Wren Murphy', 'Lennon Cook',
      'Scout Rivera'
    ])[i] as fake_name,
    (array['Starter', 'Plus', 'Premium'])[1 + ((i - 1) % 3)] as fake_tier,
    (array[
      'wireless headphones and charging cable',
      'chef knife and pantry jars',
      'yoga mat and resistance bands',
      'cleanser and mineral sunscreen',
      'mystery novel and travel memoir',
      'desk lamp and USB hub',
      'coffee grinder and tea towels'
    ])[1 + ((i - 1) % 7)] as fake_purchases
  from generate_series(1, 45) as sample(i)
)
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, tokens_used, model, provider, created_at)
select
  'personalized_recommendation',
  'Customer name: ' || fake_name || E'\n' ||
    'Demo account: DEMO-' || lpad((1000 + i)::text, 4, '0') || E'\n' ||
    'Tier: ' || fake_tier || E'\n' ||
    'Recent purchases: ' || fake_purchases || E'\n' ||
    'Reward balance: ' || (125 + i * 41) || ' points',
  'Generated two synthetic recommendations for ' || fake_name ||
    ' using fake account DEMO-' || lpad((1000 + i)::text, 4, '0') || '.',
  610 + ((i * 23) % 290),
  'gpt-4.1-mini',
  'OpenAI',
  now() - ((i + 4) % 7) * interval '1 day'
        - ((i * 67) % 990) * interval '1 minute'
from fake_profiles;

-- Expected distribution: 180 rows; 1 / 5 / 45 distinct inputs.
select
  prompt_name,
  count(*) as call_count,
  count(distinct input_text) as distinct_inputs,
  min(tokens_used) as min_tokens,
  max(tokens_used) as max_tokens,
  min(created_at) as oldest_call,
  max(created_at) as newest_call,
  sum(tokens_used) as total_tokens,
  min(model) as model,
  min(provider) as provider
from public.llm_call_logs
where created_at >= now() - interval '7 days'
group by prompt_name
order by prompt_name;
