-- LLM cache-auditing fixture for the Supabase project "llm-cache-audit".
-- Re-running this script resets only the dedicated demo table.
drop table if exists public.llm_call_logs;

create table public.llm_call_logs (
  id bigint generated by default as identity primary key,
  prompt_name text not null,
  input_text text not null,
  output_text text not null,
  input_tokens integer not null check (input_tokens between 200 and 600),
  output_tokens integer not null check (output_tokens between 100 and 400),
  model text not null,
  provider text not null,
  created_at timestamptz not null default now()
);

-- 70 calls with one exact input and one exact output: high repeat rate and
-- strong evidence that these calls are genuinely interchangeable/cacheable.
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, input_tokens, output_tokens, model, provider, created_at)
select
  'faq_bot',
  'Return the standard DemoShop FAQ answer set for the public help center.',
  'DemoShop ships standard orders in 3–5 business days. Unused items may be returned within 30 days. Billing receipts are available in Account > Orders, and account access can be restored with the password-reset link.',
  240 + ((i * 17) % 310),
  120 + ((i * 13) % 220),
  'gpt-4.1-mini',
  'OpenAI',
  now() - ((i - 1) % 7) * interval '1 day'
        - ((i * 37) % 1080) * interval '1 minute'
from generate_series(1, 70) as sample(i);

-- 65 calls across the same five dropdown-derived inputs used by the source.
-- Two-thirds use a stable description; one-third use a meaningfully different
-- description for the same category input, tempering the cacheability signal.
with category_samples as (
  select
    i,
    1 + ((i - 1) % 5) as category_index,
    (array[
      'Catalog category: electronics. Writing style: precise and feature-led.',
      'Catalog category: home-kitchen. Writing style: warm and practical.',
      'Catalog category: fitness. Writing style: energetic and motivating.',
      'Catalog category: beauty. Writing style: polished and sensory.',
      'Catalog category: books. Writing style: curious and editorial.'
    ])[1 + ((i - 1) % 5)] as category_input
  from generate_series(1, 65) as sample(i)
), category_outputs as (
  select
    i,
    category_input,
    category_index,
    (array[
      'A streamlined everyday device with intuitive controls, dependable wireless performance, a compact profile, and clearly labeled features for simple setup at home or on the go.',
      'A practical kitchen companion designed to make daily routines calmer, tidier, and easier, with a welcoming finish that suits busy counters and shared spaces.',
      'An energetic training essential built to support consistent movement, comfortable sessions, and easy transitions between home workouts, classes, and outdoor routines.',
      'A polished self-care staple with a lightweight texture, a soft botanical scent, and an elegant finish that brings a small sense of ritual to the day.',
      'An inviting read with an intriguing premise, thoughtful pacing, and memorable themes—an engaging choice for curious readers and lively book-club conversations.'
    ])[category_index] as stable_output,
    (array[
      'Built for focused work, this compact tech accessory emphasizes long battery life, quick pairing, tactile controls, and a reinforced travel case for commuters and hybrid teams.',
      'Made for weeknight cooking, this durable countertop helper combines an easy-clean surface, space-saving storage, and measured portions for faster meal preparation.',
      'Bring more momentum to interval days with sweat-resistant materials, adjustable support, visible progress markers, and a carry-friendly shape for park or studio sessions.',
      'A rich evening formula layers velvety hydration with bright citrus notes and a subtle pearlescent glow, packaged in a refillable jar for a more indulgent routine.',
      'This character-driven story follows an unlikely friendship across two cities, balancing quiet humor with sharp observations about ambition, belonging, and second chances.'
    ])[category_index] as alternate_output
  from category_samples
)
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, input_tokens, output_tokens, model, provider, created_at)
select
  'product_description_generator',
  category_input,
  case when i % 3 = 0 then alternate_output else stable_output end,
  285 + ((i * 19) % 300),
  145 + ((i * 23) % 245),
  'gpt-4.1-mini',
  'OpenAI',
  now() - ((i + 2) % 7) * interval '1 day'
        - ((i * 53) % 1020) * interval '1 minute'
from category_outputs;

-- 45 unique fake user/account profiles: near-zero repeat rate.
with fake_profiles as (
  select
    i,
    (array[
      'Avery Chen', 'Jordan Patel', 'Morgan Lee', 'Riley Garcia',
      'Casey Brown', 'Taylor Kim', 'Quinn Davis', 'Cameron Singh',
      'Skyler Wilson', 'Reese Martinez', 'Parker Nguyen', 'Rowan Clark',
      'Emerson Hall', 'Finley Robinson', 'Hayden Lewis', 'Dakota Young',
      'Sage Walker', 'Blake Hernandez', 'River King', 'Charlie Scott',
      'Alexis Green', 'Jamie Adams', 'Drew Baker', 'Kendall Nelson',
      'Robin Carter', 'Logan Mitchell', 'Arden Perez', 'Micah Roberts',
      'Ellis Brooks', 'Marley Howard', 'Remy Ward', 'Jules Torres',
      'Noel Peterson', 'Lane Gray', 'Frankie Ramirez', 'Kai James',
      'Shiloh Watson', 'Bellamy Foster', 'Ari Bennett', 'Phoenix Reed',
      'Tatum Cooper', 'Rory Bailey', 'Wren Murphy', 'Lennon Cook',
      'Scout Rivera'
    ])[i] as fake_name,
    (array['Starter', 'Plus', 'Premium'])[1 + ((i - 1) % 3)] as fake_tier,
    (array[
      'wireless headphones and charging cable',
      'chef knife and pantry jars',
      'yoga mat and resistance bands',
      'cleanser and mineral sunscreen',
      'mystery novel and travel memoir',
      'desk lamp and USB hub',
      'coffee grinder and tea towels'
    ])[1 + ((i - 1) % 7)] as fake_purchases
  from generate_series(1, 45) as sample(i)
)
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, input_tokens, output_tokens, model, provider, created_at)
select
  'personalized_recommendation',
  'Customer name: ' || fake_name || E'\n' ||
    'Demo account: DEMO-' || lpad((1000 + i)::text, 4, '0') || E'\n' ||
    'Tier: ' || fake_tier || E'\n' ||
    'Recent purchases: ' || fake_purchases || E'\n' ||
    'Reward balance: ' || (125 + i * 41) || ' points',
  'For ' || fake_name || ': recommendation one complements ' || fake_purchases ||
    '; recommendation two is selected for the ' || fake_tier ||
    ' tier and the account''s ' || (125 + i * 41) || '-point balance.',
  330 + ((i * 29) % 265),
  185 + ((i * 31) % 210),
  'gpt-4.1-mini',
  'OpenAI',
  now() - ((i + 4) % 7) * interval '1 day'
        - ((i * 67) % 990) * interval '1 minute'
from fake_profiles;

-- Verification: 180 rows total; 1 / 5 / 45 distinct inputs; FAQ has one
-- output; product has two outputs per category; personalized inputs are unique.
select
  prompt_name,
  count(*) as call_count,
  count(distinct input_text) as distinct_inputs,
  count(distinct output_text) as distinct_outputs,
  min(input_tokens) as min_input_tokens,
  max(input_tokens) as max_input_tokens,
  min(output_tokens) as min_output_tokens,
  max(output_tokens) as max_output_tokens,
  min(created_at) as oldest_call,
  max(created_at) as newest_call,
  min(model) as model,
  min(provider) as provider
from public.llm_call_logs
where created_at >= now() - interval '7 days'
group by prompt_name
order by prompt_name;
