-- Run once in a new Supabase project named llm-cache-audit.
create table if not exists public.llm_call_logs (
  id bigint generated by default as identity primary key,
  prompt_name text not null,
  input_text text not null,
  output_text text not null,
  tokens_used integer not null check (tokens_used > 0),
  created_at timestamptz not null default now()
);

-- 42 calls, one exact fixed input: high repeat rate.
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, tokens_used, created_at)
select
  'faq_bot',
  'Return the standard DemoShop FAQ answer set for the public help center.',
  (array[
    'Standard help-center summary returned: shipping, returns, billing, and account access.',
    'Public FAQ response served with the standard DemoShop support policies.',
    'Fixed FAQ answer set returned without processing any user data.'
  ])[1 + ((i - 1) % 3)],
  205 + ((i * 11) % 54),
  now() - ((i - 1) % 7) * interval '1 day'
        - ((i * 37) % 1080) * interval '1 minute'
from generate_series(1, 42) as sample(i);

-- 35 calls across five repeating dropdown inputs: medium repeat rate.
with category_samples as (
  select
    i,
    (array[
      'category=electronics;style=precise-and-feature-led',
      'category=home-kitchen;style=warm-and-practical',
      'category=fitness;style=energetic-and-motivating',
      'category=beauty;style=polished-and-sensory',
      'category=books;style=curious-and-editorial'
    ])[1 + ((i - 1) % 5)] as category_input
  from generate_series(1, 35) as sample(i)
)
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, tokens_used, created_at)
select
  'product_description_generator',
  category_input,
  'Generated a generic 90-word DemoShop catalog description for ' || category_input || '.',
  318 + ((i * 19) % 177),
  now() - ((i + 2) % 7) * interval '1 day'
        - ((i * 53) % 1140) * interval '1 minute'
from category_samples;

-- 28 distinct fake customer/account inputs: near-zero repeat rate.
with fake_profiles as (
  select
    i,
    (array[
      'Avery Chen', 'Jordan Patel', 'Morgan Lee', 'Riley Garcia',
      'Casey Brown', 'Taylor Kim', 'Quinn Davis', 'Cameron Singh',
      'Skyler Wilson', 'Reese Martinez', 'Parker Nguyen', 'Rowan Clark',
      'Emerson Hall', 'Finley Robinson', 'Hayden Lewis', 'Dakota Young',
      'Sage Walker', 'Blake Hernandez', 'River King', 'Charlie Scott',
      'Alexis Green', 'Jamie Adams', 'Drew Baker', 'Kendall Nelson',
      'Robin Carter', 'Logan Mitchell', 'Arden Perez', 'Micah Roberts'
    ])[i] as fake_name,
    (array['Starter', 'Plus', 'Premium'])[1 + ((i - 1) % 3)] as fake_tier,
    (array[
      'wireless headphones and charging cable',
      'chef knife and pantry jars',
      'yoga mat and resistance bands',
      'cleanser and mineral sunscreen',
      'mystery novel and travel memoir',
      'desk lamp and USB hub',
      'coffee grinder and tea towels'
    ])[1 + ((i - 1) % 7)] as fake_purchases
  from generate_series(1, 28) as sample(i)
)
insert into public.llm_call_logs
  (prompt_name, input_text, output_text, tokens_used, created_at)
select
  'personalized_recommendation',
  'name=' || fake_name ||
    ';account=DEMO-' || lpad((1000 + i)::text, 4, '0') ||
    ';tier=' || fake_tier ||
    ';recent_purchases=' || fake_purchases ||
    ';reward_balance=' || (125 + i * 41),
  'Generated two synthetic recommendations for ' || fake_name ||
    ' using fake account DEMO-' || lpad((1000 + i)::text, 4, '0') || '.',
  612 + ((i * 29) % 284),
  now() - ((i + 4) % 7) * interval '1 day'
        - ((i * 67) % 1190) * interval '1 minute'
from fake_profiles;

-- Expected distribution: 96 rows total; 1 / 5 / 28 distinct inputs.
select
  prompt_name,
  count(*) as call_count,
  count(distinct input_text) as distinct_inputs,
  min(created_at) as oldest_call,
  max(created_at) as newest_call,
  sum(tokens_used) as total_tokens
from public.llm_call_logs
where created_at >= now() - interval '7 days'
group by prompt_name
order by prompt_name;
